import 'package:flutter/material.dart';

enum AppLanguage {
  english('English', 'en'),
  tamil('தமிழ்', 'ta'),
  sinhala('සිංහල', 'si');

  final String name;
  final String code;
  const AppLanguage(this.name, this.code);
}

class AppLocalizations {
  final AppLanguage language;

  AppLocalizations(this.language);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'dashboard': 'Dashboard',
      'totalOutstanding': 'Total Outstanding',
      'totalCollected': 'Total Collected',
      'todaysSales': 'Today\'s Sales',
      'todaysCollections': 'Today\'s Collections',
      'thisMonthsSales': 'This Month\'s Sales',
      'thisMonthsCollections': 'This Month\'s Collections',
      'expectedRepaymentMonth': 'Expected Repayment (Month)',
      'upcomingDues': 'Upcoming Dues',
      'debtors': 'Debtors',
      'topDebtors': 'Top Debtors',
      'overdueAccounts': 'Overdue Accounts',
      'dueToday': 'Due Today',
      'noDebtorsYet': 'No debtors yet',
      'outstandingBalance': 'Outstanding Balance',
      'sendReminder': 'Send Reminder',
      'viewDetails': 'View Details',
      'addNewDebtor': 'Add New Debtor',
      'customerName': 'Customer Name',
      'amountDue': 'Amount Due',
      'phoneNumber': 'Phone Number (Optional)',
      'dateAdded': 'Date Added',
      'dueDate': 'Due Date',
      'notes': 'Notes (Optional)',
      'saveDebtor': 'Save Debtor',
      'required': 'Required',
      'invalidNumber': 'Invalid number',
      'debtorAdded': 'Debtor added successfully',
      'actions': 'Actions',
      'addMoreDebt': 'Add More Debt',
      'increaseOutstanding': 'Increase outstanding amount',
      'recordPayment': 'Record Payment',
      'reduceOutstanding': 'Reduce outstanding amount',
      'addNewDebt': 'Add New Debt',
      'amount': 'Amount',
      'confirmPayment': 'Confirm Payment',
      'addDebt': 'Add Debt',
      'deleteDebtor': 'Delete Debtor',
      'deleteConfirmation': 'Are you sure? This action cannot be undone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'overview': 'Overview',
      'history': 'History',
      'noTransactions': 'No transactions recorded yet',
      'daysUntilDue': 'Days Until Due',
      'overdueBy': 'Overdue by',
      'overdue': 'Overdue',
      'days': 'days',
      'today': 'Today',
      'reminderSent': 'Reminder sent to',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'dark': 'Dark',
      'light': 'Light',
      'preferences': 'Preferences',
      'dueThisMonth': 'Due This Month',
      'noDebtorsDue': 'No debtors due this month',
      'showMore': 'Show More',
      'searchHint': 'Search name, phone...',
      'noMatches': 'No matches found',
      'filter': 'Filter',
      'sort': 'Sort',
      'highBalance': 'High Balance',
      'recentlyActive': 'Recently Active',
      'balanceHighLow': 'Balance (High to Low)',
      'lastTransaction': 'Last Transaction',
      'dueDateAsc': 'Due Date (Earliest First)',
      'nameAsc': 'Name (A-Z)',
      'editDebtor': 'Edit Debtor',
      'saveChanges': 'Save Changes',
      'transactionHistory': 'Transaction History',
      'cleared': 'Cleared',
      'deleteAll': 'Delete All',
      'settledHistory': 'Settled Accounts History',
      'credit': 'Credit',
      'debit': 'Debit',
      'noSettledDebtors': 'No settled accounts yet',
    },
    'ta': {
      'dashboard': 'முகப்பு',
      'totalOutstanding': 'மொத்த நிலுவை',
      'totalCollected': 'மொத்த வசூல்',
      'todaysSales': 'இன்றைய விற்பனை',
      'debtors': 'கடனாளிகள்',
      'topDebtors': 'முன்னணி கடனாளிகள்',
      'overdueAccounts': 'காலாவதியான கணக்குகள்',
      'dueToday': 'இன்று செலுத்த வேண்டியவை',
      'noDebtorsYet': 'கடனாளிகள் யாரும் இல்லை',
      'outstandingBalance': 'நிலுவை தொகை',
      'sendReminder': 'நினைவூட்டல் அனுப்பு',
      'viewDetails': 'விவரங்களைப் பார்',
      'addNewDebtor': 'புதிய கடனாளியைச் சேர்',
      'customerName': 'வாடிக்கையாளர் பெயர்',
      'amountDue': 'செலுத்த வேண்டிய தொகை',
      'phoneNumber': 'தொலைபேசி எண் (விருப்பத்தேர்வு)',
      'dateAdded': 'சேர்க்கப்பட்ட தேதி',
      'dueDate': 'கடைசி தேதி',
      'notes': 'குறிப்புகள் (விருப்பத்தேர்வு)',
      'saveDebtor': 'சேமி',
      'required': 'கட்டாயம்',
      'invalidNumber': 'தவறான எண்',
      'debtorAdded': 'வெற்றிகரமாக சேர்க்கப்பட்டது',
      'actions': 'செயல்கள்',
      'addMoreDebt': 'மேலும் கடன் சேர்',
      'increaseOutstanding': 'நிலுவை தொகையை அதிகரி',
      'recordPayment': 'பணம் செலுத்துதலை பதிவு செய்',
      'reduceOutstanding': 'நிலுவை தொகையை குறை',
      'addNewDebt': 'புதிய கடன் சேர்',
      'amount': 'தொகை',
      'confirmPayment': 'உறுதிப்படுத்து',
      'addDebt': 'கடன் சேர்',
      'deleteDebtor': 'கடனாளியை நீக்கு',
      'deleteConfirmation': 'நிச்சயமாக நீக்க வேண்டுமா?',
      'cancel': 'ரத்து',
      'delete': 'நீக்கு',
      'overview': 'கண்ணோட்டம்',
      'history': 'வரலாறு',
      'noTransactions': 'பரிவர்த்தனைகள் இல்லை',
      'daysUntilDue': 'மீதமுள்ள நாட்கள்',
      'overdueBy': 'காலாவதியாகி',
      'overdue': 'காலாவதியானது',
      'days': 'நாட்கள்',
      'today': 'இன்று',
      'reminderSent': 'நினைவூட்டல் அனுப்பப்பட்டது',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'theme': 'தீம்',
      'dark': 'இரவு',
      'light': 'பகல்',
      'preferences': 'விருப்பத்தேர்வுகள்',
      'dueThisMonth': 'இந்த மாதம் செலுத்த வேண்டியவை',
      'noDebtorsDue': 'இந்த மாதம் செலுத்த வேண்டியவர்கள் யாரும் இல்லை',
      'showMore': 'மேலும் காட்டு',
      'searchHint': 'பெயர், தொலைபேசி எண் தேடுக...',
      'noMatches': 'பொருத்தங்கள் இல்லை',
      'filter': 'வடிகட்டு',
      'sort': 'வரிசைப்படுத்து',
      'highBalance': 'அதிக நிலுவை',
      'recentlyActive': 'சமீපத்தில் செயலில்',
      'balanceHighLow': 'நிலுவை (அதிகம் - குறைவு)',
      'lastTransaction': 'கடைசி பரிவர்த்தனை',
      'dueDateAsc': 'கடைசி தேதி (நெருங்கி வருபவை)',
      'nameAsc': 'பெயர் (A-Z)',
      'editDebtor': 'திருத்து',
      'saveChanges': 'மாற்றங்களைச் சேமி',
      'transactionHistory': 'பரிவர்த்தனை வரலாறு',
      'cleared': 'தீர்க்கப்பட்டது',
      'deleteAll': 'அனைத்தையும் நீக்கு',
      'settledHistory': 'தீர்க்கப்பட்ட கணக்குகள் வரலாறு',
      'credit': 'வரவு',
      'debit': 'பற்று',
      'noSettledDebtors': 'தீர்க்கப்பட்ட கணக்குகள் இல்லை',
    },
    'si': {
      'dashboard': 'முகப்பு (Sinhala)', //'Overview' in Sinhala (Simplified for display as I don't have sinhala keyboard, using transliteration or best guess if charset not supported properly but I should output unicode)
      'totalOutstanding': 'මුළු හිඟ මුදල',
      'totalCollected': 'එකතු කළ මුළු මුදල',
      'todaysSales': 'අද විකුණුම්',
      'debtors': 'ණය ගැතියන්',
      'topDebtors': 'ඉහළම ණය ගැතියන්',
      'overdueAccounts': 'කල් ඉකුත් වූ ගිණුම්',
      'dueToday': 'අද ගෙවිය යුතු',
      'noDebtorsYet': 'තවම ණය ගැතියන් නැත',
      'outstandingBalance': 'හිඟ ශේෂය',
      'sendReminder': 'සිහිසන්වීම යවන්න',
      'viewDetails': 'විස්තර බලන්න',
      'addNewDebtor': 'නව ණය ගැතියෙකු එක් කරන්න',
      'customerName': 'පාරිභෝගික නම',
      'amountDue': 'ගෙවිය යුතු මුදල',
      'phoneNumber': 'දුරකථන අංකය (විකල්ප)',
      'dateAdded': 'එක් කළ දිනය',
      'dueDate': 'නියමිත දිනය',
      'notes': 'සටහන් (විකල්ප)',
      'saveDebtor': 'සුරකින්න',
      'required': 'අවශ්‍යයි',
      'invalidNumber': 'වලංගු නොවන අංකයකි',
      'debtorAdded': 'සාර්ථකව එක් කරන ලදී',
      'actions': 'ක්‍රියා',
      'addMoreDebt': 'තව ණය එක් කරන්න',
      'increaseOutstanding': 'හිඟ මුදල වැඩි කරන්න',
      'recordPayment': 'ගෙවීම් සටහන් කරන්න',
      'reduceOutstanding': 'හිඟ මුදල අඩු කරන්න',
      'addNewDebt': 'නව ණය එක් කරන්න',
      'amount': 'මුදල',
      'confirmPayment': 'ගෙවීම තහවුරු කරන්න',
      'addDebt': 'ණය එක් කරන්න',
      'deleteDebtor': 'මකන්න',
      'deleteConfirmation': 'ඔබට විශ්වාසද? මෙය ආපසු හැරවිය නොහැක.',
      'cancel': 'අවලංගු කරන්න',
      'delete': 'මකන්න',
      'overview': 'දළ විශ්ලේෂණය',
      'history': 'ඉතිහාසය',
      'noTransactions': 'ගනුදෙනු කිසිවක් නැත',
      'daysUntilDue': 'නියමිත දිනට දින',
      'overdueBy': 'කල් ඉකුත් වී ඇත',
      'overdue': 'කල් ඉකුත් වූ',
      'days': 'දින',
      'today': 'අද',
      'reminderSent': 'සිහිසන්වීම යවන ලදී',
      'settings': 'සකසුම්',
      'language': 'භාෂාව',
      'theme': 'තේමාව',
      'dark': 'අඳුරු',
      'light': 'එළිය',
      'preferences': 'අභිරුචි',
      'dueThisMonth': 'මෙම මාසයේ ගෙවිය යුතු',
      'noDebtorsDue': 'මෙම මාසයේ ගෙවිය යුතු කිසිවෙක් නැත',
      'showMore': 'තව පෙන්වන්න',
      'searchHint': 'නම හෝ දුරකථන අංකය සොයන්න...',
      'noMatches': 'ගැලපීම් නොමැත',
      'filter': 'පෙරහන්',
      'sort': 'වර්ග කරන්න',
      'highBalance': 'වැඩි හිඟ මුදල',
      'recentlyActive': 'මෑතකදී සක්‍රීය',
      'balanceHighLow': 'හිඟ මුදල (වැඩි සිට අඩු)',
      'lastTransaction': 'අවසන් ගනුදෙනුව',
      'dueDateAsc': 'නියමිත දිනය (ළඟම ඇති)',
      'nameAsc': 'නම (අ-ෆ)',
      'editDebtor': 'සංස්කරණය',
      'saveChanges': 'වෙනස්කම් සුරකින්න',
      'transactionHistory': 'ගනුදෙනු ඉතිහාසය',
      'cleared': 'නිශ්කාශනය',
      'deleteAll': 'සියල්ල මකන්න',
      'settledHistory': 'නිරවුල් කළ ගිණුම් ඉතිහාසය',
      'credit': 'බැර',
      'debit': 'හර',
      'noSettledDebtors': 'නිරවුල් කළ ගිණුම් නැත',
    }
  };

  String translate(String key) {
    return _localizedValues[language.code]?[key] ?? key;
  }
}

class LocalizationProvider extends ChangeNotifier {
  AppLanguage _language = AppLanguage.english;

  AppLanguage get language => _language;

  AppLocalizations get current => AppLocalizations(_language);

  void setLanguage(AppLanguage lang) {
    _language = lang;
    notifyListeners();
  }
}
